// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN68Lb4MoXdt3gqcq3dS3q72mtUW3mh9U',
    appId: '1:721983613045:web:337dc87bee1dd644a6703c',
    messagingSenderId: '721983613045',
    projectId: 'my-todo-app-13198',
    authDomain: 'my-todo-app-13198.firebaseapp.com',
    storageBucket: 'my-todo-app-13198.appspot.com',
    measurementId: 'G-ZPYNF3F8Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn34Knn0QgToMxM1JzP68RQQuMrWggOGU',
    appId: '1:721983613045:android:75546385514bf369a6703c',
    messagingSenderId: '721983613045',
    projectId: 'my-todo-app-13198',
    storageBucket: 'my-todo-app-13198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFFs-xNLNo7ONOHAMEqrXn8JG9SI2ArlQ',
    appId: '1:721983613045:ios:d86786bac7e6df30a6703c',
    messagingSenderId: '721983613045',
    projectId: 'my-todo-app-13198',
    storageBucket: 'my-todo-app-13198.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFFs-xNLNo7ONOHAMEqrXn8JG9SI2ArlQ',
    appId: '1:721983613045:ios:d86786bac7e6df30a6703c',
    messagingSenderId: '721983613045',
    projectId: 'my-todo-app-13198',
    storageBucket: 'my-todo-app-13198.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN68Lb4MoXdt3gqcq3dS3q72mtUW3mh9U',
    appId: '1:721983613045:web:4013810aa42f6ca7a6703c',
    messagingSenderId: '721983613045',
    projectId: 'my-todo-app-13198',
    authDomain: 'my-todo-app-13198.firebaseapp.com',
    storageBucket: 'my-todo-app-13198.appspot.com',
    measurementId: 'G-F794KMHXHE',
  );

}